# Generated by Django 5.2.5 on 2025-08-29 08:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название модели')),
                ('description', models.TextField(blank=True, verbose_name='Описание модели')),
            ],
            options={
                'verbose_name': 'Модель автомобиля',
                'verbose_name_plural': 'Модели автомобилей',
            },
        ),
        migrations.CreateModel(
            name='EngineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название модели двигателя')),
                ('description', models.TextField(blank=True, verbose_name='Описание модели двигателя')),
            ],
            options={
                'verbose_name': 'Модель двигателя',
                'verbose_name_plural': 'Модели двигателей',
            },
        ),
        migrations.CreateModel(
            name='MainBridgeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название модели ведущего моста')),
                ('description', models.TextField(blank=True, verbose_name='Описание модели ведущего моста')),
            ],
            options={
                'verbose_name': 'Модель ведущего моста',
                'verbose_name_plural': 'Модели ведущих мостов',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceOrganisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Организация ТО')),
                ('description', models.TextField(blank=True, verbose_name='Описание организации ТО')),
            ],
            options={
                'verbose_name': 'Организация ТО',
                'verbose_name_plural': 'Организации ТО',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=252, unique=True, verbose_name='Вид ТО')),
                ('description', models.TextField(blank=True, verbose_name='Описание вида ТО')),
            ],
            options={
                'verbose_name': 'Вид ТО',
                'verbose_name_plural': 'Виды ТО',
            },
        ),
        migrations.CreateModel(
            name='ReclaimBrokePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=252, unique=True, verbose_name='Узел отказа')),
                ('description', models.TextField(blank=True, verbose_name='Описание узла отказа')),
            ],
            options={
                'verbose_name': 'Узел отказа',
                'verbose_name_plural': 'Узлы отказа',
            },
        ),
        migrations.CreateModel(
            name='ReclaimRestoreMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=252, unique=True, verbose_name='Способ восстановления')),
                ('description', models.TextField(blank=True, verbose_name='Описание способа восстановления')),
            ],
            options={
                'verbose_name': 'Способ восстановления',
                'verbose_name_plural': 'Способы восстановления',
            },
        ),
        migrations.CreateModel(
            name='SubBridgeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название модели управляемого моста')),
                ('description', models.TextField(blank=True, verbose_name='Описание модели управляемого моста')),
            ],
            options={
                'verbose_name': 'Модель управляемого моста',
                'verbose_name_plural': 'Модели управляемых мостов',
            },
        ),
        migrations.CreateModel(
            name='TransmissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название модели трансмиссии')),
                ('description', models.TextField(blank=True, verbose_name='Описание модели трансмиссии')),
            ],
            options={
                'verbose_name': 'Модель трансмиссии',
                'verbose_name_plural': 'Модели трансмиссий',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(max_length=252, unique=True, verbose_name='Заводской № машины')),
                ('engine_number', models.CharField(max_length=252, verbose_name='Заводской № двигателя')),
                ('trans_number', models.CharField(max_length=252, verbose_name='Заводской № трансмиссии')),
                ('main_bridge_number', models.CharField(max_length=252, verbose_name='Заводской № ведущего моста')),
                ('sub_bridge_number', models.CharField(max_length=252, verbose_name='Заводской № управляемого моста')),
                ('contract_number_date', models.CharField(max_length=252, verbose_name='Договор поставки: №, дата')),
                ('send_date', models.DateField(verbose_name='Дата отгрузки с завода')),
                ('receiver', models.CharField(max_length=50, verbose_name='Грузополучатель')),
                ('address', models.CharField(max_length=50, verbose_name='Адрес поставки')),
                ('equipment', models.TextField(max_length=504, verbose_name='Комплектация (доп. опции)')),
                ('service_company', models.ForeignKey(limit_choices_to={'groups__name': 'ServiceOrganization'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serviced_cars', to=settings.AUTH_USER_MODEL, verbose_name='Сервисная компания')),
                ('user', models.ForeignKey(limit_choices_to={'groups__name': 'Client'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Владелец (клиент)')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Main.carmodel', verbose_name='Модель машины')),
                ('engine_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Main.enginemodel', verbose_name='Модель двигателя')),
                ('main_bridge_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Main.mainbridgemodel', verbose_name='Модель ведущего моста')),
                ('sub_bridge_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Main.subbridgemodel', verbose_name='Модель управляемого моста')),
                ('trans_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Main.transmissionmodel', verbose_name='Модель трансмиссии')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField(verbose_name='Дата проведения ТО')),
                ('worked_for', models.IntegerField(verbose_name='Наработка, м/час')),
                ('order_number', models.CharField(max_length=252, verbose_name='№ заказ-наряда')),
                ('order_date', models.DateField(verbose_name='Дата заказ-наряда')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.car', verbose_name='Машина')),
                ('service_company', models.ForeignKey(limit_choices_to={'groups__name': 'ServiceOrganization'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Сервисная компания')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Main.maintenancetype', verbose_name='Вид ТО')),
            ],
            options={
                'verbose_name': 'Техническое обслуживание',
                'verbose_name_plural': 'Технические обслуживания',
            },
        ),
        migrations.CreateModel(
            name='Reclaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broke_date', models.DateField(verbose_name='Дата отказа')),
                ('worked_for', models.IntegerField(verbose_name='Наработка, м/час')),
                ('broke_description', models.TextField(max_length=504, verbose_name='Описание отказа')),
                ('used_spare_parts', models.TextField(blank=True, max_length=252, verbose_name='Используемые запасные части')),
                ('restore_date', models.DateField(verbose_name='Дата восстановления')),
                ('downtime', models.IntegerField(editable=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='Время простоя техники')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.car', verbose_name='Машина')),
                ('service_company', models.ForeignKey(limit_choices_to={'groups__name': 'ServiceOrganization'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Сервисная компания')),
                ('broke_place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Main.reclaimbrokeplace', verbose_name='Узел отказа')),
                ('restore_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Main.reclaimrestoremethod', verbose_name='Способ восстановления')),
            ],
            options={
                'verbose_name': 'Рекламация',
                'verbose_name_plural': 'Рекламации',
            },
        ),
    ]
